# Generated by Django 5.1.6 on 2025-02-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('accuracy', models.IntegerField(default=0, null=True)),
                ('power', models.IntegerField(default=0, null=True)),
                ('pp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemonId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('health', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('sp_attack', models.IntegerField(default=0)),
                ('sp_defence', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('moves', models.ManyToManyField(to='Pokedex.move')),
                ('types', models.ManyToManyField(to='Pokedex.type')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pokedex.type'),
        ),
    ]
