# Generated by Django 5.1.1 on 2025-01-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(verbose_name=100)),
                ('accuracy', models.SmallIntegerField()),
                ('power', models.SmallIntegerField()),
                ('pp', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=25)),
                ('number', models.SmallIntegerField()),
                ('health', models.SmallIntegerField()),
                ('attack', models.SmallIntegerField()),
                ('defence', models.SmallIntegerField()),
                ('sp_attack', models.SmallIntegerField()),
                ('sp_defence', models.SmallIntegerField()),
                ('speed', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=250)),
            ],
        ),
    ]
