# Generated by Django 5.1.1 on 2025-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0002_stats_remove_pokemon_attack_remove_pokemon_defence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='stats',
            name='attack',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='defence',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='health',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='sp_attack',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='sp_defence',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='speed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
