# Generated by Django 5.1.1 on 2025-01-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0003_rename_picture_pokemon_image_alter_stats_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Move', to='Pokedex.type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(related_name='Pokemon', to='Pokedex.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pokemon', to='Pokedex.stats'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='Pokemon', to='Pokedex.type'),
        ),
    ]
