# Generated by Django 5.1.1 on 2025-01-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0004_move_type_pokemon_moves_pokemon_stat_pokemon_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
