# Generated by Django 5.1.1 on 2025-02-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pokedex', '0005_remove_pokemon_moves_remove_pokemon_stat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('accuracy', models.IntegerField()),
                ('power', models.IntegerField()),
                ('pp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defence', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemonId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('moves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pokedex.move')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pokedex.stat')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pokedex.type')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pokedex.type'),
        ),
    ]
