# Generated by Django 5.1.1 on 2025-02-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pokedex.type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='moves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pokedex.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pokedex.stat'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pokedex.type'),
        ),
    ]
