# Generated by Django 5.1.1 on 2025-02-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0013_alter_move_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(blank=True, null=True, to='Pokedex.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='Pokedex.type'),
        ),
    ]
