# Generated by Django 5.1.1 on 2025-02-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0014_remove_pokemon_moves_remove_pokemon_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='accuracy',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
