# Generated by Django 5.1.1 on 2025-02-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0015_alter_move_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='pokemonId',
            field=models.IntegerField(default=0),
        ),
    ]
