# Generated by Django 5.1.1 on 2025-02-12 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0016_stat_pokemonid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='stat',
        ),
        migrations.AddField(
            model_name='stat',
            name='pokemon',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Pokedex.pokemon'),
            preserve_default=False,
        ),
    ]
