# Generated by Django 5.1.6 on 2025-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0020_pokemon_attack_pokemon_defence_pokemon_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
